### ISSUE TITLE
Performance audit and speed enhancements

### ISSUE THREAD

**Issue by domyen** [storybookjs/frontpage#12]
This is a general request to help improve site speed and performance. You can find the deploy preview of `master` [**👉here👈**](https://dazzling-chandrasekhar-c337aa.netlify.com/)

We get a lot of stuff out of the box from Gatsby, but I'm sure inefficiencies remain. 

[**PageSpeed Insights score**](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdazzling-chandrasekhar-c337aa.netlify.com%2F)
Update 12/19: 91/100 
Update 1/28: 92/100

**Comment by isaac-martin** [comment]
I'll have a look at this

**Comment by hakimelek** [comment]
Here is some little things I have noticed:

* It seems like `gatsby-plugin-web-font-loader` is causing FOUT. I prefer loading the font manually using react-helmet on the pages and pre-connect to google fonts before any js is loaded.
* I see that `gatsby-image` is setup but the img tags are not using it. If we serve images using WebP, it should slash some kbs on supported browsers.
* The SVG logo could be optimized some more, ~2kb but will make your first paint a bit faster maybe.
* Lighthouse is mostly complaining about interactivity and that's caused by the hydration of the page (which is not really needed here) but we can try to hack it. I recently found out about [react-lazy-hydration](https://www.npmjs.com/package/react-lazy-hydration) and seems to be promising.

**Comment by lucas-carl** [comment]
## Ensure text remains visible during webfont load

I think we should use the font-display attribute for loading the webfonts. But i don't know how one would implement it in the code.

<img width="877" alt="Screenshot 2019-03-20 at 09 14 38" src="https://user-images.githubusercontent.com/13051923/54669046-a9082300-4af0-11e9-9119-14f74cdc5762.png">

https://developers.google.com/web/updates/2016/02/font-display

**Comment by domyen** [comment]
@lucas-carl I looked into that, unfortunately it's not straightforward to implement with google fonts.

**Comment by dakebl** [comment]
@domyen I think we can look into the font loading again, now that google fonts have shipped font-display? https://addyosmani.com/blog/google-fonts-font-display/

**Comment by dakebl** [comment]
I've created a PR for Typography.js, to add the config option of `fontDisplay` for this but for the moment we can handle it using the `styles` object. I'll raise a PR

**Comment by domyen** [comment]
Closing this now. Thanks everyone. Our pagespeed score is now 97/100 for desktop.
