### ISSUE TITLE
Undefined contributors on homepage

### ISSUE THREAD

**Issue by shilman** [storybookjs/frontpage#121]
https://twitter.com/pkcodes/status/1288606244626993153?s=21

https://twitter.com/pkcodes/status/1288609560014532612?s=21

**Comment by dakebl** [comment]
@shilman @domyen I've raised PR #122 to add a hardcoded version of the contributor count back to the site. 

The plugin I had made to get the data was broken by the GitHub redesign and seemed to have been failing silently since by looks of it. I've now retired the package all together as a result, so I've added a hardcoded contributor count to the sitemeta dataset, which makes it accessible everywhere. I also replaced the urls with those stored in sitemeta, as you had already duplicated the data there.
