### ISSUE TITLE
Dead Link in Composition Docs

### ISSUE THREAD

**Issue by toddgaunt** [storybookjs/frontpage#330]
The following [link](https://storybook.js.org/docs/react/sharing/storybook-publish) at the top of this [page](https://storybook.js.org/docs/react/sharing/storybook-composition) is dead.

**Comment by jonniebigodes** [comment]
@toddgaunt thanks for the time you took to create this issue we appreciate it. I've just pushed a pull request to fix this issue. If you wouldn't mind, for any documentation issues similar to this one, please open an issue in the Storybook repo and mention me so that I can take a look at it and follow up with you, as this repo is for the Storybook website. 

Hope you don't mind but I'm closing this issue as it's already fixed.

Have a great weekend.

Stay safe

**Comment by toddgaunt** [comment]
Hey @jonniebigodes not sure what you mean? I'd be happy to report elsewhere, but I just followed the issue link that the link 404'd at. Isn't the repo for the website where this is appropriate to make an issue?

**Comment by jonniebigodes** [comment]
Hi @toddgaunt and to answer your question, yes this is the repo for the website and related issues to it. But we don't track documentation issues here, but rather in the [Storybook monorepo](https://github.com/storybookjs/storybook) instead. 

Sorry about the confusion.

Stay safe
