### ISSUE TITLE
Badges in addon README displayed weirdly

### ISSUE THREAD

**Issue by JesusTheHun** [storybookjs/frontpage#560]
**Describe the bug**

![Screenshot 2022-05-12 at 11 35 05](https://user-images.githubusercontent.com/94478/168040458-64e0f28f-b6f9-415b-ad30-6e36659be676.png)

The README on GitHub : https://github.com/JesusTheHun/storybook-addon-react-router-v6/blob/main/README.md
The raw README : https://raw.githubusercontent.com/JesusTheHun/storybook-addon-react-router-v6/main/README.md

**Comment by prantlf** [comment]
The badges appear to be wrapped to multiple lines. Another example: https://storybook.js.org/addons/storybook-multilevel-sort/

---

![obrazek](https://github.com/storybookjs/frontpage/assets/733193/8d48dad0-35ea-48e6-a6b3-0251b1ede764)

---

Concretely this problem is caused by making images blocks, which are placed on new lines. The page above contains one hyperlink with two badges. The badges are rendered on two lines:

---

![obrazek](https://github.com/storybookjs/frontpage/assets/733193/7b97a410-21b9-49ae-9f78-30f7a93816fe)

---

A fix could be not forcing images inside hyperlinks to be rendered on new lines:

---

![obrazek](https://github.com/storybookjs/frontpage/assets/733193/fbba0b09-6c4d-4b76-b24c-bfa7cffc9572)

---

But such change would have to be made carefully not to break anything.

I've made a change in https://github.com/prantlf/storybook-multilevel-sort/blob/master/README.md to place each image to its own hyperlink. It's probably the most usual case. Once Storybook.js gets synchronised, let's see if the three badges remain on the same line.

---

I found that two badges work: And two badges below a picture work too: https://storybook.js.org/addons/chromatic/

---

![obrazek](https://github.com/storybookjs/frontpage/assets/733193/147ac645-cad7-4356-9c9d-bd992f25998e)

---

And a big icon at the top of the readme too: https://storybook.js.org/addons/msw-storybook-addon/

---

![obrazek](https://github.com/storybookjs/frontpage/assets/733193/a4ecc3fb-d08e-4e5b-a3ed-e07263f31cf5)
